# Generated by Django 4.2.30 on 2026-07-10 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='line1',
            new_name='delivery_details',
        ),
        migrations.RemoveField(
            model_name='address',
            name='line2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='county',
            field=models.CharField(choices=[('Baringo', 'Baringo'), ('Bomet', 'Bomet'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Embu', 'Embu'), ('Garissa', 'Garissa'), ('Homa Bay', 'Homa Bay'), ('Isiolo', 'Isiolo'), ('Kajiado', 'Kajiado'), ('Kakamega', 'Kakamega'), ('Kericho', 'Kericho'), ('Kiambu', 'Kiambu'), ('Kilifi', 'Kilifi'), ('Kirinyaga', 'Kirinyaga'), ('Kisii', 'Kisii'), ('Kisumu', 'Kisumu'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Laikipia', 'Laikipia'), ('Lamu', 'Lamu'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Meru', 'Meru'), ('Migori', 'Migori'), ('Mombasa', 'Mombasa'), ("Murang'a", "Murang'a"), ('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Nandi', 'Nandi'), ('Narok', 'Narok'), ('Nyamira', 'Nyamira'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Samburu', 'Samburu'), ('Siaya', 'Siaya'), ('Taita-Taveta', 'Taita-Taveta'), ('Tana River', 'Tana River'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Trans Nzoia', 'Trans Nzoia'), ('Turkana', 'Turkana'), ('Uasin Gishu', 'Uasin Gishu'), ('Vihiga', 'Vihiga'), ('Wajir', 'Wajir'), ('West Pokot', 'West Pokot')], default='Nairobi', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='phone_alt',
            field=models.CharField(blank=True, default='', max_length=13, validators=[django.core.validators.RegexValidator('^(?:\\+254|0)(?:7|1)\\d{8}$', 'Enter a valid Kenyan phone number e.g. +254712345678 or 0712345678.')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[' -][A-Za-z]+)*$", 'Enter a valid city or town name, letters only.')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Kenya', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='full_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:['-][A-Za-z]+)*(?: [A-Za-z]+(?:['-][A-Za-z]+)*)+$", 'Enter your full name (first and last name), letters only.')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^(?:\\+254|0)(?:7|1)\\d{8}$', 'Enter a valid Kenyan phone number e.g. +254712345678 or 0712345678.')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Kenyan postal codes are exactly 5 digits e.g. 00100.')]),
        ),
    ]
