"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load secret credentials from mysite/.env (gitignored) into the environment.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ika-yqt(1$d@r-+@a*kyivxl2f97yzdo2f--9c37e(!$cmegq#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'myapp',
    "cart",
    'mathfilters',
    'users',
    'orders',
    'rest_framework',
    'corsheaders',
    'drf_spectacular',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CORS headers must be added before any middleware that can produce
    # a response, so browsers see them even on redirects and errors
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# PostgreSQL when credentials exist in .env (the normal case - dev matches
# production); falls back to SQLite so a fresh clone still runs with zero setup.
if os.environ.get('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME'),
            'USER': os.environ.get('DB_USER'),
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Kenya-first store: timestamps display in East Africa Time. Storage
# stays UTC because USE_TZ = True - only presentation changes.
TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# where @login_required sends visitors who are not logged in
LOGIN_URL = 'login'

# sessions last 2 weeks: login AND cart survive browser restarts -
# persistent carts are an e-commerce conversion feature, not a bug
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14

# Email credentials come from environment variables so they are never
# committed to git. Set EMAIL_HOST_USER and EMAIL_HOST_PASSWORD (a Gmail
# App Password) in your shell before running the server.
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
else:
    # No credentials set: print emails to the terminal instead of sending,
    # so registration still works during local development.
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# --- API (Phase 1) ---

# Browsers block JS on one origin from reading responses from another
# unless the server allows it. Allow ONLY the Vite dev server for now;
# the production frontend domain gets added in Phase 6. Never use a
# wildcard here - that would let any website script against our API.
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',    # Vite's default dev address
    'http://127.0.0.1:5173',    # same server, but the browser treats
                                # localhost and 127.0.0.1 as different origins
]

REST_FRAMEWORK = {
    # every list endpoint is paginated unless it opts out - page size 12
    # fills the product grid (4 columns x 3 rows) exactly
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
    # one error shape everywhere: {'error': ...} (see mysite/api.py)
    'EXCEPTION_HANDLER': 'mysite.api.api_exception_handler',
    # brute-force protection: only views that declare a throttle_scope
    # are throttled (login, register, verify-email), per IP
    'DEFAULT_THROTTLE_CLASSES': ['rest_framework.throttling.ScopedRateThrottle'],
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/min',
        'register': '10/min',
        'verify-email': '10/min',
    },
    # drf-spectacular generates the OpenAPI schema behind /api/docs/
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Shop API',
    'DESCRIPTION': 'JSON API for the Shop e-commerce platform: '
                   'products, session cart, orders, and session-cookie auth.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}